### PR TITLE
Initial import of internal packages

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds some `internal/` packages that are going to be used by the protocol code in subsequent PRs.

- internal/congestion: get/set methods to switch the congestion control algorithm on a socket
- internal/netx: a utility function to extract the underlying file descriptor from a plain/TLS `net.Conn`
- internal/persistence: a wrapper around os.File to create result files with standard paths

Also, to test the conditionally-built code under `congestion` I imported the same Github Actions workflow that can be seen working at https://github.com/robertodauria/msak/actions (I think this will only start working after it's merged into `main` -- EDIT: this actually worked in the PR, too) that runs `go test ./...` under Linux, Windows and MacOS.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/msak/1)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
This is nice. A few comments for nits and suggestions for clarifications or simplifications in the future.

> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/1#-:-NJ69B797C6TCfDdRoze:bacgbwo)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`internal/congestion/congestion.go` line 21 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ61btf5SMh_sElVigF:-NJ61btf5SMh_sElVigG:b-1ugwpx) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/congestion/congestion.go#L21)):*
> ```Go
> }
> 
> func Get(fp *os.File) (string, error) {
> ```

nit: What does Get do? 
___
*[`internal/congestion/congestion_linux.go` line 62 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ64NyVERDgr2EvPqUc:-NJ64NyVERDgr2EvPqUd:btj1w8a) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/congestion/congestion_linux.go#L62)):*
> ```Go
> }
> 
> func getMaxBandwidthAndMinRTT(fp *os.File) (inetdiag.BBRInfo, error) {
> ```

Not for this PR but consider how we can normalize the logic here so we have one implementation rather than N. This looks largely repeated from https://github.com/m-lab/ndt-server/blob/0823c174338d4ea8b0476476d5a237b00d8bed83/bbr/bbr_linux.go And, there is a third variant in tcp-info that maps the C struct directly to the Go struct. https://github.com/m-lab/tcp-info/blob/main/snapshot/snapshot.go#L218 - Again - not for this PR, just observing a proliferation of implementations for the same/similar operation.
___
*[`internal/congestion/congestion_linux_test.go` line 25 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ67vTb1JCqFuOFOX5k:-NJ67vTb1JCqFuOFOX5l:b-nyelsw) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/congestion/congestion_linux_test.go#L25)):*
> ```Go
> 		t.Errorf("cannot get the socket's cc: %v", err)
> 	}
> 	fmt.Println(cc)
> ```

Under what conditions will this test fail? Is there a set of valid values that we can check `cc` against? (e.g. the list of available ones like use below?)

Alternately, since `TestSet` uses `Get`, there may only need to be one `Test*` here.
___
*[`internal/congestion/congestion_stub_test.go` line 14 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ68hnI-mtk5pPKD3s3:-NJ68hnJEXyIuZhUcMSO:b-3vqcaf) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/congestion/congestion_stub_test.go#L14)):*
> ```Go
> 	// This is unsupported on non-Linux systems.
> 	err := Set(&os.File{}, "")
> 	if err == nil {
> ```

nit: I suggest asserting the expected error value here. The test fails if the error is anything other than `ErrNoSupport`. (similarly below)
___
*[`internal/netx/netx.go` line 10 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ5xAik4R0cO84wXjHq:-NJ5xAik4R0cO84wXjHr:b-jcldds) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/netx/netx.go#L10)):*
> ```Go
> )
> 
> func GetFile(conn net.Conn) (*os.File, error) {
> ```

nit: please add docstring.
___
*[`internal/persistence/file.go` line 37 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ5yMch8T57-HdAEMip:-NJ5yMch8T57-HdAEMiq:bpt2of9) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/persistence/file.go#L37)):*
> ```Go
> func New(datadir, datatype, subtest, uuid string) (*DataFile, error) {
> 	file, err := newDataFile(datadir, datatype, subtest, uuid)
> 	if err != nil {
> ```

Optional: `newDataFile` already provides this return guarantee. `return newDataFile(...)` appears to be equivalent. Is more planned for this constructor?
___
*[`internal/persistence/file.go` line 49 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ5z23XCYMWMOusRH-1:-NJ5z23XCYMWMOusRH-2:bheyov) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/persistence/file.go#L49)):*
> ```Go
> 		return err
> 	}
> 	_, err = df.fp.Write(data)
> ```

note: Marshal does not add a newline. Is it expected that the caller uses `Write()` only once? Are other operations planned? Is this package interface closer to `os.WriteFile` or https://pkg.go.dev/encoding/json#NewEncoder ?
___
*[`internal/persistence/file_test.go` line 1 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ5zxF8CSJWfgyO3oIt:-NJ5zxF99qFx0Uhp1ibv:b-b8xrl8) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/persistence/file_test.go#L1)):*
> ```Go
> package persistence
> ```

What isn't testable with a blackbox test, e.g. `package persistence_test` ?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/1)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`internal/congestion/congestion_linux.go` line 62 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ64NyVERDgr2EvPqUc:-NJLSx6b9ETblxwzYJN9:bb6rskq) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/congestion/congestion_linux.go#L62)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Not for this PR but consider how we can normalize the logic here so we have one implementation rather than N. This looks largely repeated from https://github.com/m-lab/ndt-server/blob/0823c174338d4ea8b0476476d5a237b00d8bed83/bbr/bbr_linux.go And, there is a third variant in tcp-info that maps the C struct directly to the Go struct. https://github.com/m-lab/tcp-info/blob/main/snapshot/snapshot.go#L218 - Again - not for this PR, just observing a proliferation of implementations for the same/similar operation.
</blockquote></details>

ACK.
___
*[`internal/congestion/congestion_linux_test.go` line 25 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ67vTb1JCqFuOFOX5k:-NJLT4fU6lMUm-_U5nP7:b-mq9cbh) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/congestion/congestion_linux_test.go#L25)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Under what conditions will this test fail? Is there a set of valid values that we can check `cc` against? (e.g. the list of available ones like use below?)

Alternately, since `TestSet` uses `Get`, there may only need to be one `Test*` here.
</blockquote></details>

There's only one `GetSet` test now, which takes the available cc algorithms in the test environment and tries setting/getting each of them. At least two (reno and cubic) are available pretty much everywhere this test is expected to run, but it would theoretically work even with just one algorithm -- with the caveat that there is no way to verify that `Get` actually did something, in that case.
___
*[`internal/persistence/file.go` line 37 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ5yMch8T57-HdAEMip:-NJLXaI4EK6RwI7SgEDO:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/persistence/file.go#L37)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Optional: `newDataFile` already provides this return guarantee. `return newDataFile(...)` appears to be equivalent. Is more planned for this constructor?
</blockquote></details>

Done.
___
*[`internal/persistence/file.go` line 49 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ5z23XCYMWMOusRH-1:-NJLXet9ErTTryV1xsSz:b-pmefep) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/persistence/file.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

note: Marshal does not add a newline. Is it expected that the caller uses `Write()` only once? Are other operations planned? Is this package interface closer to `os.WriteFile` or https://pkg.go.dev/encoding/json#NewEncoder ?
</blockquote></details>

I changed the interface as discussed on VC.

Is there a reason why this should add a newline at the end of the file? (e.g. does jostler require it?). It's always a single JSON object per output file.
___
*[`internal/persistence/file_test.go` line 1 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ5zxF8CSJWfgyO3oIt:-NJLbYmy3DjjgPbPfFUI:bsv6asy) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/persistence/file_test.go#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What isn't testable with a blackbox test, e.g. `package persistence_test` ?
</blockquote></details>

I only needed internal fields access to get the file path with `fp.Name()`. I've changed the `DataFile` struct quite a bit so all the path components + the path itself + the file size are public fields and changed this test to be blackbox.

**Review by stephen-soltesz — COMMENTED** [review]
Thank you, a few small comments.

> Reviewed 1 of 11 files at r1, 2 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/1#-:-NJM96GU-za5G9FQaXgU:bbw8j0i)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`internal/congestion/congestion_linux_test.go` line 25 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ67vTb1JCqFuOFOX5k:-NJLe62CBgjkmAQpalCT:b-9755fn) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/congestion/congestion_linux_test.go#L25)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

There's only one `GetSet` test now, which takes the available cc algorithms in the test environment and tries setting/getting each of them. At least two (reno and cubic) are available pretty much everywhere this test is expected to run, but it would theoretically work even with just one algorithm -- with the caveat that there is no way to verify that `Get` actually did something, in that case.
</blockquote></details>

Thank you!
___
*[`internal/congestion/congestion_stub_test.go` line 25 at r3](https://reviewable.io/reviews/m-lab/msak/1#-NJLeLTn-redU6SxiAqD:-NJLeLTn-redU6SxiAqE:brv2n58) ([raw file](https://github.com/m-lab/msak/blob/13bab16f4f3618e11caf13206f74f5c87e927b3f/internal/congestion/congestion_stub_test.go#L25)):*
> ```Go
> 		t.Errorf("unexpected value")
> 	}
> 	if err == ErrNoSupport {
> ```

is this correct?

I expected `!= ErrNoSupport`. Does this condition match the message below?

Same below.
___
*[`internal/netx/netx.go` line 10 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ5xAik4R0cO84wXjHq:-NJLeXYx6ntOAJ7yTqul:b-jcldds) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/netx/netx.go#L10)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: please add docstring.
</blockquote></details>

nit: please add docstring.
___
*[`internal/persistence/file.go` line 49 at r1](https://reviewable.io/reviews/m-lab/msak/1#-NJ5z23XCYMWMOusRH-1:-NJLeepB6dHzj567UxYR:b-o4hbxb) ([raw file](https://github.com/m-lab/msak/blob/10e2146482ce85dcb1f1f6d14acf8c248a89df98/internal/persistence/file.go#L49)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I changed the interface as discussed on VC.

Is there a reason why this should add a newline at the end of the file? (e.g. does jostler require it?). It's always a single JSON object per output file.
</blockquote></details>

Not if it's a single JSON object.
The new line is needed for JSONL.
___
*[`internal/persistence/file_test.go` line 36 at r3](https://reviewable.io/reviews/m-lab/msak/1#-NJM8TzG7tenHN-X-yFk:-NJM8TzG7tenHN-X-yFl:b3j23os) ([raw file](https://github.com/m-lab/msak/blob/13bab16f4f3618e11caf13206f74f5c87e927b3f/internal/persistence/file_test.go#L36)):*
> ```Go
> 
> 	// Check the generated path.
> 	prefix := fmt.Sprintf("testdata/type/%s/type-subtest-", time.Now().Format("2006/01/02"))
> ```

Very low probability; just observing that two calls to time.Now() could have different dates and cause the test to be flaky.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/1)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`internal/congestion/congestion_stub_test.go` line 25 at r3](https://reviewable.io/reviews/m-lab/msak/1#-NJLeLTn-redU6SxiAqD:-NJQVGQL6TafFmk4AYIg:bhzwcwo) ([raw file](https://github.com/m-lab/msak/blob/13bab16f4f3618e11caf13206f74f5c87e927b3f/internal/congestion/congestion_stub_test.go#L25)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

is this correct?

I expected `!= ErrNoSupport`. Does this condition match the message below?

Same below.
</blockquote></details>

I think you were still seeing an older revision -- it's fixed now.
___
*[`internal/persistence/file_test.go` line 36 at r3](https://reviewable.io/reviews/m-lab/msak/1#-NJM8TzG7tenHN-X-yFk:-NJetrVlAIbvGRC9BmgZ:b-5qrdpu) ([raw file](https://github.com/m-lab/msak/blob/13bab16f4f3618e11caf13206f74f5c87e927b3f/internal/persistence/file_test.go#L36)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Very low probability; just observing that two calls to time.Now() could have different dates and cause the test to be flaky.
</blockquote></details>

Thoughts on the workaround?

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/1#-:-NJevdGa55CMIvnq8_6H:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`internal/persistence/file_test.go` line 36 at r3](https://reviewable.io/reviews/m-lab/msak/1#-NJM8TzG7tenHN-X-yFk:-NJevST-2lyHasVCeTMv:b-b72zi8) ([raw file](https://github.com/m-lab/msak/blob/13bab16f4f3618e11caf13206f74f5c87e927b3f/internal/persistence/file_test.go#L36)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Thoughts on the workaround? 
</blockquote></details>

WriteDataFile could accept the timestamp as a parameter.

**Pull request merged**
