### PR TITLE
Add throughput1 client library

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds the client library for MSAK's `throughput1` protocol. It's meant to be a (fully functional) MVP, with more nice-to-have features to be added in subsequent PRs. To test it:

```
# defaults: 2 BBR streams, 3s duration, no delay, plaintext, production Locate instance and servers
go run ./cmd/msak-client
```

Things not included:
- A flag for multi-server testing (to run each stream against a different server)
- Aggregate throughput in HumanReadable's output -- unclear how it should be computed, since each stream intentionally _excludes_ the TLS and WS handshakes, while it would be more correct to include them in this case. I'm considering to add a second network byte counter that includes that overhead, but that will involve a design update and a separate PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/msak/26)

### CODE REVIEW

**Review by nkinkade — COMMENTED** [review]
@robertodauria: I checked out your branch and ran the test, and it seemed to work as intended. And the code _seems_ fine to me, but I'm not confident I can give you a meaningful review of the code in terms of best-practices and good or bad form, or suggest better ways of doing things. Consider the original epoxy-extensions PR I put together for you a few months ago. The code worked as it was in the original PR, but as you found, the naming was bad, the layout was bad and just generally it was not quality code. I'm worried that I'm not able to offer suggestions and concerns that might be obvious to Stephen or Cristina?

What do you think? Sorry to take a full day to review this PR, only to say this.

> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/26#-:-NfID07jBk-NdFhfdJyX:b-qyjxxh)* status: 0 of 1 approvals obtained

**Comment by robertodauria** [comment]
@nkinkade I appreciate you taking the time to test and review the code. Thanks!                        

I'm going to add a second reviewer on this PR, but I'm still interested in any comments or ideas you might have. I've found that engaging in code reviews also improves one's own understanding of the language and code design, and any effort to increase code quality is always welcome.

Generally speaking, something that helped me a lot when approaching Go code reviews are these
resources:                   

- [Effective Go](https://go.dev/doc/effective_go) - "tips for writing clear, idiomatic Go code"
- [Go code review comments](https://github.com/golang/go/wiki/CodeReviewComments) - a collection of good practices and things to look for in code reviews
- [Test comments](https://github.com/golang/go/wiki/TestComments) - like the above, but focused on how to write good tests

If you have time, I'd love getting a second eye on how I'm following these conventions!

(For example, one thing I noticed while looking at my code again after a day is that I forgot to add docstrings on some exported identifiers - e.g. the Locator interface, or pretty much every field in `Throughput1Client` :sweat_smile: )

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/26)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/msak-client/client.go` line 17 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRC74e6-vk2TtZVsak:-NfRUhdE8dNIjLV-4JXW:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L17)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should this be a const?
</blockquote></details>

Done.
___
*[`cmd/msak-client/client.go` line 28 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRDanbCkBPwK47NMxJ:-NfRUinNAb5wURPCLZ_9:b3vp4rw) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L28)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Does this need to be unique for all measurements?
</blockquote></details>

The only case when `-mid` is passed directly (as opposed to coming from Locate) is when running the client with `-server=<hostname>` against a server with token verification disabled -- basically, only during development. A random UUID seemed a better default than a static string, or having to provide a fake MID manually every time.
___
*[`cmd/msak-client/client.go` line 36 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRBzv38TpJ_MTkRR_Q:-NfRWAAwD08yL3ckTGsv:b-eyd884) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L36)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Why -1? Perhaps add a comment.
</blockquote></details>

`flagDelay` adds a delay between one stream and the next one, and this check is to prevent configurations such as `-delay 5s -duration 5s -streams 2`  which would not allow the second stream to even start. The number of delays is `streams - 1`.
___
*[`cmd/msak-client/client.go` line 37 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRD3zT4jfFEQIMQuFE:-NfRZRYZ68qvQSsszYVK:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L37)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Would `log.Fatal` be more concise?
</blockquote></details>

Done.
___
*[`pkg/client/client.go` line 91 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRDrHN5oGUmhPLsUvs:-NfRbxbgATQDzHKdyd5t:b8r289k) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/pkg/client/client.go#L91)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

This sentence sounds a bit redundant. I'm not sure I understand what the `Emitter` does from the description alone.
</blockquote></details>

:) how about now?
___
*[`pkg/client/client.go` line 34 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRFWZd88Qfo33Bm9j-:-NfRZpXF9_dfN2cJFYOH:b-dsw0ww) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L34)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What's the rationale for these defaults being different from those in the `main` package.
</blockquote></details>

Now the command-line flags' defaults are set to these consts.
___
*[`pkg/client/client.go` line 107 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRHdouCHWIuBKkK0Ev:-NfRd5WQ7v-QPyr1z2tq:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L107)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Please add docstrings for these.
</blockquote></details>

Done.
___
*[`pkg/client/client.go` line 136 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRHsJgB4k4wL5D7bUA:-NfRdqqb-mbUQX4dDKpg:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L136)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Add this as a default in the set of default constants defined above?
</blockquote></details>

Done.
___
*[`pkg/client/client.go` line 185 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRMNNa-yShnEIsKgtc:-NfRdrXH54QDcAhhylYl:b-wx5kh6) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L185)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What is this doing?
</blockquote></details>

That is magic I borrowed from ndt7-client-go :smile:

`targets` is a slice of Locate's `v2.Target` that caches results from Locate's invocation the first time `nextURLFromLocate` is called.
`tIndex` maps strings like `(ws|wss):///throughput1/v1/download` to an index which is used to get the next target from `targets` on each subsequent call to `nextURLFromLocate`. It takes me a good couple of minutes to figure out how it works every time, to be honest. What do you think would help making it clearer?
___
*[`pkg/client/client.go` line 198 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRKaID2OiWdo3COyRT:-NfRjdLqCQpBPxTOZ39G:b-zc4tay) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L198)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What if the result for this call is "invalid"?
</blockquote></details>

Considering that value is always set in this file to either `spec.SubtestDownload` or `spec.SubtestUpload`, I changed `getPathForSubtest` to panic on an invalid subtest.
___
*[`pkg/client/client.go` line 210 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRKvzm7WxbwPoiLgx9:-NfRloU8111xtnefBD4d:bqern9u) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L210)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What flag sets `ServiceURL`?
</blockquote></details>

I've actually removed it entirely.
___
*[`pkg/client/client.go` line 240 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRNLIOAF7roAvrD6nT:-NfRm1lW4sCgcXEPhrHn:boz9ai4) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L240)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What happens if the test ends before 100ms (e.g., [early exit](https://github.com/m-lab/ndt7-client-go/pull/92))?
</blockquote></details>

At least one Measurement from the receiver side (client to server for download test, server to client for upload tests) should be available to show a result. :thinking:

I can implement the same solution you implemented in ndt7-client-go and that takes care of download tests. However, I am not sure how upload tests could work in this case. Trusting `Application.BytesSent` or `Network.BytesSent` is generally unreliable, even more so on such a short test, but the client will likely not receive any counterflow message before ~250ms.
___
*[`pkg/client/emitter.go` line 62 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRJklX6HV_QFzQlazM:-NfRo1Jy21il3FXIIPHY:bow13g9) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/emitter.go#L62)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

Done. (added comment)

**Review by robertodauria — COMMENTED** [review]
Moving this to a separate repo is something I'm considering as well. Meanwhile, I think I've addressed all your comments -- PTAL again? Thanks!

> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/26#-:-NfT8hhH5sCOjhK79kNT:b-wrvnw5)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/msak-client/client.go` line 55 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfREF6fASHWoRVqrj24:-NfT6CXn79kEuAKjhQp2:b-mhf8vi) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L55)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

You could combine these opts in a `ClientOpts` object that is passed into `client.New` to be set. That way all the `Client` fields can be set in one place.
</blockquote></details>

Done. I called it `client.Config`  but the general idea is the same. Thoughts?
___
*[`cmd/msak-client/client.go` line 58 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfREnIR-H4Od6_bXKue:-NfT6OGZ4-9B7yzkgY71:broo39j) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L58)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Does it make sense to have a function that calls both of these?
</blockquote></details>

Hmm. I'm going to add two `-download` and `-upload`  flags to enable or disable the corresponding test, so those two will always be called separately in `main()`.
___
*[`pkg/client/client.go` line 91 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRDrHN5oGUmhPLsUvs:-NfT7Mr759D8Kl3yFBtY:b-7hkkpc) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/pkg/client/client.go#L91)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

:) how about now?
</blockquote></details>

(This field and the corresponding docstring have been moved to config.go)
___
*[`pkg/client/emitter.go` line 10 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRJTth69VNvuFeEHM_:-NfT8aK24y4Z7368uASs:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/emitter.go#L10)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Please add docstrings.
</blockquote></details>

Done.

**Review by cristinaleonr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/26)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`cmd/msak-client/client.go` line 17 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRC74e6-vk2TtZVsak:-NfWD0ZZ3gA8LnxwGG0n:bv576mw) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L17)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! I've been thinking about how we've struggled to track down the exact client integration responsible for the periodic clients because the identifier is the default "ndt7-client-go-cmd/0.5.0 ndt7-client-go/0.5.0". What do you think about forcing the client to set this field to a non-empty string?
___
*[`cmd/msak-client/client.go` line 28 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRDanbCkBPwK47NMxJ:-NfWCSKiAg1YrLpOLKwI:b-t0rcl0) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L28)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

The only case when `-mid` is passed directly (as opposed to coming from Locate) is when running the client with `-server=<hostname>` against a server with token verification disabled -- basically, only during development. A random UUID seemed a better default than a static string, or having to provide a fake MID manually every time.
</blockquote></details>

Makes sense. I guess I was thinking more so what happens to the data/BQ analyses if, say, there is a client that always passes in the same `-mid` or there is a collision for some reason?
___
*[`cmd/msak-client/client.go` line 36 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRBzv38TpJ_MTkRR_Q:-NfWE3eD2R1Fk3yTdN6f:b-n36lqw) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L36)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

`flagDelay` adds a delay between one stream and the next one, and this check is to prevent configurations such as `-delay 5s -duration 5s -streams 2`  which would not allow the second stream to even start. The number of delays is `streams - 1`.
</blockquote></details>

I see. Thanks for adding a comment.
___
*[`cmd/msak-client/client.go` line 55 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfREF6fASHWoRVqrj24:-NfWEXLU6MDl8XXHh9Pt:bcg1pu2) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L55)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Done. I called it `client.Config`  but the general idea is the same. Thoughts?
</blockquote></details>

Looks great. Thanks!
___
*[`pkg/client/client.go` line 91 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRDrHN5oGUmhPLsUvs:-NfWEVLW8Ev6d0OTNdYb:b-2hka24) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/pkg/client/client.go#L91)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

(This field and the corresponding docstring have been moved to config.go)
</blockquote></details>

Perfect, thank you!
___
*[`pkg/client/client.go` line 185 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRMNNa-yShnEIsKgtc:-NfWGNSX8rNaWvdbqlDi:b-8hvvin) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L185)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

That is magic I borrowed from ndt7-client-go :smile:

`targets` is a slice of Locate's `v2.Target` that caches results from Locate's invocation the first time `nextURLFromLocate` is called.
`tIndex` maps strings like `(ws|wss):///throughput1/v1/download` to an index which is used to get the next target from `targets` on each subsequent call to `nextURLFromLocate`. It takes me a good couple of minutes to figure out how it works every time, to be honest. What do you think would help making it clearer?
</blockquote></details>

I knew this looked familiar. Maybe we can add a comment explaining that so we'll all remember when we see it next time?
___
*[`pkg/client/client.go` line 210 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRKvzm7WxbwPoiLgx9:-NfWErIOBsLNdk8DwzCb:bc4vwkg) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L210)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I've actually removed it entirely.
</blockquote></details>

Thanks! In the future, this functionality would be helpful to add back (e.g., my machine will not pass my location to AppEngine in the Locate request, so I would need to pass in a custom Locate URL with my location in the URL params).

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/26)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/msak-client/client.go` line 17 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRC74e6-vk2TtZVsak:-NfWSD0G1bA7_ubST4PG:bik4vex) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L17)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Thanks! I've been thinking about how we've struggled to track down the exact client integration responsible for the periodic clients because the identifier is the default "ndt7-client-go-cmd/0.5.0 ndt7-client-go/0.5.0". What do you think about forcing the client to set this field to a non-empty string?
</blockquote></details>

I suspect in that case the client integration might just be running the `ndt7-client-go` binary itself.
I changed `client.New()` to panic if passed an empty string and added a corresponding unit test.
___
*[`cmd/msak-client/client.go` line 28 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRDanbCkBPwK47NMxJ:-NfWVxde57OkDAhhfMdM:bxwaq7) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L28)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Makes sense. I guess I was thinking more so what happens to the data/BQ analyses if, say, there is a client that always passes in the same `-mid` or there is a collision for some reason?
</blockquote></details>

A client cannot pass a custom MID unless token verification is disabled on the server. When token verification is enabled, the MID is extracted from the signed JWT that comes from Locate, and the measurement won't start if the signature doesn't match. Does this address your concern?
___
*[`pkg/client/client.go` line 210 at r4](https://reviewable.io/reviews/m-lab/msak/26#-NfRKvzm7WxbwPoiLgx9:-NfWiqyk8quUUzXonSrL:by8lm0d) ([raw file](https://github.com/m-lab/msak/blob/b9d430c0535efc0817ed76a0fb1da556291a2c83/pkg/client/client.go#L210)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Thanks! In the future, this functionality would be helpful to add back (e.g., my machine will not pass my location to AppEngine in the Locate request, so I would need to pass in a custom Locate URL with my location in the URL params).
</blockquote></details>

Already discussed on Slack, but for awareness: this can be done via `-locate.url`, which is still available.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/26#-:-NfX6glh2-7AYlSOd4Wf:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[`cmd/msak-client/client.go` line 28 at r3](https://reviewable.io/reviews/m-lab/msak/26#-NfRDanbCkBPwK47NMxJ:-NfX6HSn4SRt5obqU5Mn:bb77uf3) ([raw file](https://github.com/m-lab/msak/blob/61c38207382bcee7332e6c1ad2d91c4b4c0e4a13/cmd/msak-client/client.go#L28)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

A client cannot pass a custom MID unless token verification is disabled on the server. When token verification is enabled, the MID is extracted from the signed JWT that comes from Locate, and the measurement won't start if the signature doesn't match. Does this address your concern?
</blockquote></details>

Yes!

**Pull request merged**
