### PR TITLE
Add prometheus metrics to the ndt8 handlers

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds the following Prometheus metrics:
- `msak_ndt8_tests_total{direction}`: number of tests that started, by direction (download/upload)
- `msak_ndt8_connection_errors_total{direction, error}`: number of connections that failed before starting a test, by direction and error type
- `msak_ndt8_file_writes_total{direction, status}`: number of files written to disk, by test direction and status (ok/error)

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/msak/13)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/13)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`internal/handler/handler.go` line 48 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWsys1p9psYkAPSg9t4:-NWsys1p9psYkAPSg9t5:bmtehxy) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L48)):*
> ```Go
> 			Help:      "Counter of ndt8 tests",
> 		},
> 		[]string{"direction"},
> ```

My instinct is to recommend including an additional label here also to distinguish between success and errors easily.

As currently written the "total number of tests (successful or otherwise)" requires two metrics, i.e. `sum(msak_ndt8_tests_total) + sum(msak_ndt8_connection_errors_total)` rather than an expression like `sum(msak_ndt8_tests_total)` (or similar).

I created a breakdown like this in ndt-server so we could see aggregate counts easily or dive into detailed errors https://github.com/m-lab/ndt-server/tree/main/ndt7/metrics. I'm not saying do the same thing but I wanted to cite that as an example. In particular, `ndt7_client_test_results_total` which has a short set of states ("ok", "error", etc) and `ndt7_client_sender_errors_total` which has more information about the error cases.
___
*[`internal/handler/handler.go` line 190 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1jh53BWlcfXL050Y:-NWt1jh53BWlcfXL050Z:bl3unk8) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L190)):*
> ```Go
> 		err = conn.SetCC(requestCC)
> 		if err != nil {
> 			log.Info("Failed to set cc", "ctx", fmt.Sprintf("%p", req.Context()),
> ```

Counting these events could also be instructive even if they're not fatal errors.
___
*[`internal/handler/handler.go` line 221 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1P1B3MEbfWf-3Xon:-NWt1P1B3MEbfWf-3Xoo:b-q1nksl) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L221)):*
> ```Go
> 	}()
> 
> 	testsTotal.WithLabelValues(string(kind)).Inc()
> ```

Are these all successes?
___
*[`internal/handler/handler.go` line 260 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1-b8AQQ-ncw9XSOM:-NWt1-b9AAzL7wYWPW6f:b-jfqap1) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L260)):*
> ```Go
> 				log.Info("Connection closed unexpectedly", "context",
> 					fmt.Sprintf("%p", timeout), "error", err)
> 				// TODO: Add Prometheus metric
> ```

Do we need a metric or label on `testsTotal` here to distinguish between two kinds of results? e.g. successes and premature errors? Should these be counted as successes?

**Review by robertodauria — COMMENTED** [review]
PTAL again?

> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/13#-:-NoNFndr4TxyK8Q2DRee:bch9hor)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`internal/handler/handler.go` line 48 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWsys1p9psYkAPSg9t4:-NoND36a5pDiOsWB8IMg:b4bodhm) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L48)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

My instinct is to recommend including an additional label here also to distinguish between success and errors easily.

As currently written the "total number of tests (successful or otherwise)" requires two metrics, i.e. `sum(msak_ndt8_tests_total) + sum(msak_ndt8_connection_errors_total)` rather than an expression like `sum(msak_ndt8_tests_total)` (or similar).

I created a breakdown like this in ndt-server so we could see aggregate counts easily or dive into detailed errors https://github.com/m-lab/ndt-server/tree/main/ndt7/metrics. I'm not saying do the same thing but I wanted to cite that as an example. In particular, `ndt7_client_test_results_total` which has a short set of states ("ok", "error", etc) and `ndt7_client_sender_errors_total` which has more information about the error cases.
</blockquote></details>

Now there are two metrics, similarly to how it's done in ndt-server:
- `client_connections_total`: every connection that reaches the ul/dl handler. `status` indicates if there was an error (i.e. missing mandatory parameter) or it successfully reached the websocket upgrade
- `tests_total`: every connection that upgraded to websocket. Must correspond to `file_writes_total` since from that point an archive is created in any case
___
*[`internal/handler/handler.go` line 190 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1jh53BWlcfXL050Y:-NoNDwXY1UFRiQaMX3UP:b5uh8gx) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L190)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Counting these events could also be instructive even if they're not fatal errors.
</blockquote></details>

I suspect I'd need a separate metric, since the existing ones would otherwise count a connection where we failed to set cc twice... `msak_throughput1_errors_total{error="..."}` ?
___
*[`internal/handler/handler.go` line 221 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1P1B3MEbfWf-3Xon:-NoNEPwH5WwvkIE65RuI:b-a2ujfl) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L221)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are these all successes?
</blockquote></details>

Changed.
___
*[`internal/handler/handler.go` line 260 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1-b8AQQ-ncw9XSOM:-NoNETya9LNxEHZmvLIR:b-ueb72f) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L260)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do we need a metric or label on `testsTotal` here to distinguish between two kinds of results? e.g. successes and premature errors? Should these be counted as successes?
</blockquote></details>

I've tried to clarify what the possible cases are:
- close errors
  - normal close
  - unexpected close (i.e. EOF)
- non-close errors (something went wrong in the protocol code)

There is still a remaining issue though: when the client closes the connection after 5s it does so abruptly, which is the counted as `close-error`. Not sure if I should consider this an actual error or include `CloseAbnormalClosure` in the "ok" case. Thoughts?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/13)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`internal/handler/handler.go` line 48 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWsys1p9psYkAPSg9t4:-NoNH1hq3Cw0Ab_5JlDN:b-amcn81) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L48)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Now there are two metrics, similarly to how it's done in ndt-server:
- `client_connections_total`: every connection that reaches the ul/dl handler. `status` indicates if there was an error (i.e. missing mandatory parameter) or it successfully reached the websocket upgrade
- `tests_total`: every connection that upgraded to websocket. Must correspond to `file_writes_total` since from that point an archive is created in any case
</blockquote></details>

Since `client_connections_total` is just about the websocket upgrade path, please consider a rename to make this self-describing. Also please hint in the help text.

e.g. `client_websocket_upgrades_total` or similar
___
*[`internal/handler/handler.go` line 190 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1jh53BWlcfXL050Y:-NoNGdZn8r2WhMQ35pop:b827ajm) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L190)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I suspect I'd need a separate metric, since the existing ones would otherwise count a connection where we failed to set cc twice... `msak_throughput1_errors_total{error="..."}` ?
</blockquote></details>

What if every connection fails to set the requested CC? Can we monitor this?
___
*[`internal/handler/handler.go` line 260 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1-b8AQQ-ncw9XSOM:-NoOcgn58z5-wULVcdqC:b-nqlwdm) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L260)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I've tried to clarify what the possible cases are:
- close errors
  - normal close
  - unexpected close (i.e. EOF)
- non-close errors (something went wrong in the protocol code)

There is still a remaining issue though: when the client closes the connection after 5s it does so abruptly, which is the counted as `close-error`. Not sure if I should consider this an actual error or include `CloseAbnormalClosure` in the "ok" case. Thoughts?
</blockquote></details>

I recommend adding an issue and TODO to record abnormal close errors. This is something always missing from ndt7. If the server knows that something that shouldn't have happened happened, we should record this in the results.
___
*[`internal/handler/handler.go` line 56 at r3](https://reviewable.io/reviews/m-lab/msak/13#-NoNHxaYA5jZBvYOU2gW:-NoNHxaYA5jZBvYOU2gX:b-imxn3j) ([raw file](https://github.com/m-lab/msak/blob/2306746c7a02531ec153933cacc2cc882aacd153/internal/handler/handler.go#L56)):*
> ```Go
> 			Namespace: "msak",
> 			Subsystem: "throughput1",
> 			Name:      "tests_total",
> ```

Clarifying:  `sum(client_connections_total{status="ok"}) == sum(tests_total)` ?
___
*[`internal/handler/handler.go` line 65 at r3](https://reviewable.io/reviews/m-lab/msak/13#-NoNI6WYBdIFKWue_nou:-NoNI6WYBdIFKWue_nov:b813mke) ([raw file](https://github.com/m-lab/msak/blob/2306746c7a02531ec153933cacc2cc882aacd153/internal/handler/handler.go#L65)):*
> ```Go
> 			Namespace: "msak",
> 			Subsystem: "throughput1",
> 			Name:      "file_writes_total",
> ```

Clarifying: `sum(tests_total) == sum(file_writes_total)`?
___
*[`internal/handler/handler.go` line 252 at r3](https://reviewable.io/reviews/m-lab/msak/13#-NoOdAFO5Wte6U5x2UBH:-NoOdAFO5Wte6U5x2UBI:b-sg0ljt) ([raw file](https://github.com/m-lab/msak/blob/2306746c7a02531ec153933cacc2cc882aacd153/internal/handler/handler.go#L252)):*
> ```Go
> 		case <-timeout.Done():
> 			// If the test has timed out count it as a success and return.
> 			testsTotal.WithLabelValues(string(kind), "ok").Inc()
> ```

Is this truly the same as "websocket.CloseNormalClosure"?

Which is the expected common case? server timeout or client close? Which ever is the expected common case, call "ok". The other, please qualify with something like "ok-foo" whatever foo is, e.g. maybe "close-ok" below for the normal close case.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/13)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`internal/handler/handler.go` line 48 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWsys1p9psYkAPSg9t4:-NolxLle4_ayZdA2cjlu:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L48)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since `client_connections_total` is just about the websocket upgrade path, please consider a rename to make this self-describing. Also please hint in the help text.

e.g. `client_websocket_upgrades_total` or similar
</blockquote></details>

Done.
___
*[`internal/handler/handler.go` line 190 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1jh53BWlcfXL050Y:-NolyIq7EFHM1ZVoLcZr:b3dg9e3) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L190)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What if every connection fails to set the requested CC? Can we monitor this?
</blockquote></details>

I agree that this would be useful to have.  :slightly_smiling_face: What do you think of the name above?
___
*[`internal/handler/handler.go` line 260 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1-b8AQQ-ncw9XSOM:-NolyxCyCy74yngg0VPn:bsozf4h) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L260)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend adding an issue and TODO to record abnormal close errors. This is something always missing from ndt7. If the server knows that something that shouldn't have happened happened, we should record this in the results.
</blockquote></details>

Hmm... both the server and the client should close the connection cleanly with a proper `CloseMessage` but it not generally expected that every client implementation does so. When the client terminates the connection in advance (e.g. CTRL+C, to replicate this scenario) the server sees a `websocket.CloseAbnormalClosure` (unexpected EOF) not a `websocket.CloseNormalClosure`.  These "abnormal" closures are totally expected and should not be classified as an error. I've updated the code and added a comment explaining this better.
___
*[`internal/handler/handler.go` line 56 at r3](https://reviewable.io/reviews/m-lab/msak/13#-NoNHxaYA5jZBvYOU2gW:-NolxPJ12bMtn9AIYjF_:b3tuhxm) ([raw file](https://github.com/m-lab/msak/blob/2306746c7a02531ec153933cacc2cc882aacd153/internal/handler/handler.go#L56)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Clarifying:  `sum(client_connections_total{status="ok"}) == sum(tests_total)` ?
</blockquote></details>

Yes. Every connection that reached the websocket upgrade successfully is counted in `tests_total`. 
___
*[`internal/handler/handler.go` line 65 at r3](https://reviewable.io/reviews/m-lab/msak/13#-NoNI6WYBdIFKWue_nou:-Noly2Lz73uF1P2gEzto:b-lu468) ([raw file](https://github.com/m-lab/msak/blob/2306746c7a02531ec153933cacc2cc882aacd153/internal/handler/handler.go#L65)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Clarifying: `sum(tests_total) == sum(file_writes_total)`?
</blockquote></details>

Yes. Every connection that reached the websocket upgrade successfully must generate an archive file, regardless of the outcome of the test.
___
*[`internal/handler/handler.go` line 252 at r3](https://reviewable.io/reviews/m-lab/msak/13#-NoOdAFO5Wte6U5x2UBH:-Nolykn598xqUUALsBuP:bpdzi0v) ([raw file](https://github.com/m-lab/msak/blob/2306746c7a02531ec153933cacc2cc882aacd153/internal/handler/handler.go#L252)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this truly the same as "websocket.CloseNormalClosure"?

Which is the expected common case? server timeout or client close? Which ever is the expected common case, call "ok". The other, please qualify with something like "ok-foo" whatever foo is, e.g. maybe "close-ok" below for the normal close case.
</blockquote></details>

Both `CloseNormalClosure` and `CloseAbnormalClosure` are (somewhat unfortunately) expected -- see below.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/13)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`internal/handler/handler.go` line 190 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1jh53BWlcfXL050Y:-Nom29-O9csXR-gaIonm:b8i27lt) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L190)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I agree that this would be useful to have.  :slightly_smiling_face: What do you think of the name above?
</blockquote></details>

I don't understand. I can imagine this being a separate metric. I recommend adding one. I agree we don't want to double count errors on an existing metric. Sorry if I've misunderstood.
___
*[`internal/handler/handler.go` line 260 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1-b8AQQ-ncw9XSOM:-Nom2dIA8EOtRx8tYfQv:b2lozfr) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L260)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Hmm... both the server and the client should close the connection cleanly with a proper `CloseMessage` but it not generally expected that every client implementation does so. When the client terminates the connection in advance (e.g. CTRL+C, to replicate this scenario) the server sees a `websocket.CloseAbnormalClosure` (unexpected EOF) not a `websocket.CloseNormalClosure`.  These "abnormal" closures are totally expected and should not be classified as an error. I've updated the code and added a comment explaining this better.
</blockquote></details>

"This protocol has no errors" seems suspicious to me, no? Doesn't have to be this PR. Maybe create a TODO referencing an issue.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/13)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`internal/handler/handler.go` line 190 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1jh53BWlcfXL050Y:-NomrrCJExaTu-iMQ0ug:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L190)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't understand. I can imagine this being a separate metric. I recommend adding one. I agree we don't want to double count errors on an existing metric. Sorry if I've misunderstood.
</blockquote></details>

Done.
___
*[`internal/handler/handler.go` line 260 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1-b8AQQ-ncw9XSOM:-Nomrs-Q6FN98TD03txS:b65jwc3) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L260)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"This protocol has no errors" seems suspicious to me, no? Doesn't have to be this PR. Maybe create a TODO referencing an issue.
</blockquote></details>

Done. Discussed on VC, we'll add a field to the archival data to mark tests that should be considered invalid (e.g. if the requested duration does not match the actual stream duration)

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/13#-:-NomtK1f2-bXhYmSq2bI:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[`internal/handler/handler.go` line 260 at r1](https://reviewable.io/reviews/m-lab/msak/13#-NWt1-b8AQQ-ncw9XSOM:-NomsyvNBQaOwlGEq8n9:b-bfbziy) ([raw file](https://github.com/m-lab/msak/blob/faf3de8fe44f9c67b4f434f90132b70f5af63ba6/internal/handler/handler.go#L260)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Done. Discussed on VC, we'll add a field to the archival data to mark tests that should be considered invalid (e.g. if the requested duration does not match the actual stream duration)
</blockquote></details>

I'd be satisfied with just documenting the trade off in an issue for now. e.g. bake the policy into msak server or increase complexity of bq filtering and analysis.

**Pull request merged**
