### PR TITLE
Add minimal download throughput1 client & update README

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new self-contained, single-stream, minimal download client that contains the core logic of contacting the Locate API, opening an MSAK WebSocket connection, and downloading until the server closes the connection (or client times out). Required options include flags, e.g. -bytes, -duration, -cc.

This type of minimal client is helpful as a reference for a skilled developer to translate patterns from Go into their own language.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/msak/31)

### CODE REVIEW

**Review by robertodauria — APPROVED** [review]
:lgtm: - Thank you!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/31#-:-NndMBq23iZapgqhvFKv:bsjzsje)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Review by robertodauria — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/31)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`README.md` line 99 at r1](https://reviewable.io/reviews/m-lab/msak/31#-NndNPaz2iqx4dWhN8xu:-NndNPb-8eoFkkKzlfWh:bp00bip) ([raw file](https://github.com/m-lab/msak/blob/68060751661f44793c6ddfae27e28096c6bc51d2/README.md#L99)):*
> ```Markdown
> 
> The maximum difference between the application and network sent sizes should be
> equal to the `spec.MaxScaledMessageSize` or 1MB, and the maximum difference
> ```

Not sure about this sentence: `Application.BytesSent` is WS payload, which can go up to 1MB, but `Network.BytesSent` is `WS payload + WS header (+ TLS header if applicable)` since that is what is eventually written to the `net.Conn`. Also, a 1MB message may correspond to multiple WebSocket frames, thus increasing the headers overhead. I'd say the maximum difference is `spec.MaxScaledMessageSize + WebSocket/TLS headers size` - what do you think?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/31)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @robertodauria)

___
*[`README.md` line 99 at r1](https://reviewable.io/reviews/m-lab/msak/31#-NndNPaz2iqx4dWhN8xu:-NndjKsI5etKsE9TwD72:b-evc137) ([raw file](https://github.com/m-lab/msak/blob/68060751661f44793c6ddfae27e28096c6bc51d2/README.md#L99)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Not sure about this sentence: `Application.BytesSent` is WS payload, which can go up to 1MB, but `Network.BytesSent` is `WS payload + WS header (+ TLS header if applicable)` since that is what is eventually written to the `net.Conn`. Also, a 1MB message may correspond to multiple WebSocket frames, thus increasing the headers overhead. I'd say the maximum difference is `spec.MaxScaledMessageSize + WebSocket/TLS headers size` - what do you think?
</blockquote></details>

I agree. I've updated the description accordingly.

I've also updated the client to report the `applicationBytesReceived` as a final summary line, to use kernel BytesAcked instead of BytesSent and include RTT.

**Review by robertodauria — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/31#-:-Nne3q0F3FXzWxqSKDlE:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Pull request merged**
