### PR TITLE
Import results and spec packages

### PR DESCRIPTION
**Pull request by robertodauria**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/msak/2)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
High level comments.

> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/2#-:-NLM3uQq4xS8MWu_y4UK:boknj9h)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`pkg/ndtm/results/results.go` line 12 at r2](https://reviewable.io/reviews/m-lab/msak/2#-NLM2d52EdDq--f3Xo9M:-NLM2d536J9HQhHZabCq:bekeeef) ([raw file](https://github.com/m-lab/msak/blob/13fd16a70c5d66753dcd955f3bf9e70e0da4e3c6/pkg/ndtm/results/results.go#L12)):*
> ```Go
> // NDTMResult is the struct that is serialized as JSON to disk as the archival
> // record of an ndt-m test.
> type NDTMResult struct {
> ```

Clarifying: Is this the top-most structure for an MSAK result?

I understand MSAK will allow multiple TCP streams. Will there be multiple instances of NDTMResult, one per stream?

When I see GitShortCommit/Version / MeasurementID (all common to the complete test) I expected to see a repeated structure for the individual streams in the test. Currently, UUID is also a top level field.
___
*[`pkg/ndtm/results/results.go` line 29 at r2](https://reviewable.io/reviews/m-lab/msak/2#-NLM3Dwi1ylh_QUE-lR2:-NLM3Dwi1ylh_QUE-lR3:biuopbo) ([raw file](https://github.com/m-lab/msak/blob/13fd16a70c5d66753dcd955f3bf9e70e0da4e3c6/pkg/ndtm/results/results.go#L29)):*
> ```Go
> 	EndTime time.Time
> 	// CongestionControl is the congestion control algorithm used by the flow.
> 	CongestionControl string
> ```

This field is also in ConnectionInfo. Do we need it in both places?
___
*[`pkg/ndtm/results/results.go` line 64 at r2](https://reviewable.io/reviews/m-lab/msak/2#-NLM3NR52yA6Je9ZV0mt:-NLM3NR6CWVDtApujbqm:be86wwg) ([raw file](https://github.com/m-lab/msak/blob/13fd16a70c5d66753dcd955f3bf9e70e0da4e3c6/pkg/ndtm/results/results.go#L64)):*
> ```Go
> 	// CC is the congestion algorithm used by the sender of the Measurement
> 	// that includes this struct.
> 	CC string
> ```

Under what conditions do we know this value? I can imagine if the server sets the CC during a download we know for sure. Is this field also used for uploads or is NDTM only for downloads?

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/2)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`pkg/ndtm/results/results.go` line 12 at r2](https://reviewable.io/reviews/m-lab/msak/2#-NLM2d52EdDq--f3Xo9M:-NLM4bQUCqWGG6U6znZo:bx2bip) ([raw file](https://github.com/m-lab/msak/blob/13fd16a70c5d66753dcd955f3bf9e70e0da4e3c6/pkg/ndtm/results/results.go#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Clarifying: Is this the top-most structure for an MSAK result?

I understand MSAK will allow multiple TCP streams. Will there be multiple instances of NDTMResult, one per stream?

When I see GitShortCommit/Version / MeasurementID (all common to the complete test) I expected to see a repeated structure for the individual streams in the test. Currently, UUID is also a top level field.
</blockquote></details>

Yes, this is the structure that's written to disk as JSON, and it represents a single TCP flow. Multiple flows belonging to a single measurement will have the same MeasurementID, but different UUIDs.

NDTMResult rows will be loaded into BigQuery as they are, then one or more views will aggregate the results (e.g. by appending each measurement to an array and computing the aggregate throughput).

This is a design choice that also allows multi-server measurements, where NDTMResults are split among several machines and can be only re-united later on. I'm not sure what a better place for `GitShortCommit` / `Version` might be, given this design constraint. It's _theoretically_ possible that two servers run different versions of msak-server at test time. Whether such a measurement should be considered valid or not is something we can determine _ex post_ (in BigQuery).
___
*[`pkg/ndtm/results/results.go` line 29 at r2](https://reviewable.io/reviews/m-lab/msak/2#-NLM3Dwi1ylh_QUE-lR2:-NLM6l6uB8fO8a7pKxDl:barl3oj) ([raw file](https://github.com/m-lab/msak/blob/13fd16a70c5d66753dcd955f3bf9e70e0da4e3c6/pkg/ndtm/results/results.go#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This field is also in ConnectionInfo. Do we need it in both places?
</blockquote></details>

Practically, probably no. `NDTMResult.CongestionControl` is the same as `ConnectionInfo.CC` when `Measurement.Origin` is `sender`.  I would leave the latter as it's the most flexible one (some clients might have access to it and send it to the server when uploading).
___
*[`pkg/ndtm/results/results.go` line 64 at r2](https://reviewable.io/reviews/m-lab/msak/2#-NLM3NR52yA6Je9ZV0mt:-NLM9zrA2lpBCKU3MAQq:b-pr26ln) ([raw file](https://github.com/m-lab/msak/blob/13fd16a70c5d66753dcd955f3bf9e70e0da4e3c6/pkg/ndtm/results/results.go#L64)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Under what conditions do we know this value? I can imagine if the server sets the CC during a download we know for sure. Is this field also used for uploads or is NDTM only for downloads?
</blockquote></details>

It's for both.

Most clients won't have any way to know the CC they're using while uploading, this field is there for the clients that do know and for the download measurements (since the server always knows).

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/2)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`pkg/ndtm/results/results.go` line 12 at r2](https://reviewable.io/reviews/m-lab/msak/2#-NLM2d52EdDq--f3Xo9M:-NLO8ADT1KZr4LTuRZTq:bmctmfk) ([raw file](https://github.com/m-lab/msak/blob/13fd16a70c5d66753dcd955f3bf9e70e0da4e3c6/pkg/ndtm/results/results.go#L12)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Yes, this is the structure that's written to disk as JSON, and it represents a single TCP flow. Multiple flows belonging to a single measurement will have the same MeasurementID, but different UUIDs.

NDTMResult rows will be loaded into BigQuery as they are, then one or more views will aggregate the results (e.g. by appending each measurement to an array and computing the aggregate throughput).

This is a design choice that also allows multi-server measurements, where NDTMResults are split among several machines and can be only re-united later on. I'm not sure what a better place for `GitShortCommit` / `Version` might be, given this design constraint. It's _theoretically_ possible that two servers run different versions of msak-server at test time. Whether such a measurement should be considered valid or not is something we can determine _ex post_ (in BigQuery).
</blockquote></details>

Are these requirements documented? It sounds like you've thought about these issues and the current structure is an expression of that. That's good.

When we try to review logic/structure before seeing a design or requirements or establishing a shared understanding another way, we have to rely on our best estimate for how things will work. And, we may see different trade offs or simply a partial picture. Ideally design tradeoff discussions occur in design docs because they're much easier to iterate there with lower sunk costs than code (sometimes).

Would you be willing to start a doc that summaries the objective, motivations (limitations of earlier approaches that motivate the need for msak) and a list of requirements derived from these limitations? You probably know all of these already, or build on some of the ERC proposal, so it should go quickly.

This system will also be the first user of the autoloading pipeline. So it's possible there are interactions that are easier to see at the design stage, e.g. associating annotation data or other sidecar data with msak measurements, or new requirements placed on the data pipeline generally.
___
*[`pkg/ndtm/results/results.go` line 64 at r2](https://reviewable.io/reviews/m-lab/msak/2#-NLM3NR52yA6Je9ZV0mt:-NLO7r1G6qrS4OgnzGXr:b-d9cngm) ([raw file](https://github.com/m-lab/msak/blob/13fd16a70c5d66753dcd955f3bf9e70e0da4e3c6/pkg/ndtm/results/results.go#L64)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

It's for both.

Most clients won't have any way to know the CC they're using while uploading, this field is there for the clients that do know and for the download measurements (since the server always knows).
</blockquote></details>

How does/will the client request a given CC for the server to use?

**Review by robertodauria — COMMENTED** [review]
Now we have a design document answering your questions (and hopefully many more :slightly_smiling_face:). I've updated this PR to align with that design document.

I considered reusing ndt-server's `metadata` package but that seemed a huge dependency just for the `NameValue` struct.

PTAL again?

> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/2#-:-NNvfEqiAesADaoOqcT0:bglnlzh)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/2)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`pkg/ndtm/results/results.go` line 12 at r2](https://reviewable.io/reviews/m-lab/msak/2#-NLM2d52EdDq--f3Xo9M:-NNvg_Mp9LR9PoB2akXF:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/13fd16a70c5d66753dcd955f3bf9e70e0da4e3c6/pkg/ndtm/results/results.go#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are these requirements documented? It sounds like you've thought about these issues and the current structure is an expression of that. That's good.

When we try to review logic/structure before seeing a design or requirements or establishing a shared understanding another way, we have to rely on our best estimate for how things will work. And, we may see different trade offs or simply a partial picture. Ideally design tradeoff discussions occur in design docs because they're much easier to iterate there with lower sunk costs than code (sometimes).

Would you be willing to start a doc that summaries the objective, motivations (limitations of earlier approaches that motivate the need for msak) and a list of requirements derived from these limitations? You probably know all of these already, or build on some of the ERC proposal, so it should go quickly.

This system will also be the first user of the autoloading pipeline. So it's possible there are interactions that are easier to see at the design stage, e.g. associating annotation data or other sidecar data with msak measurements, or new requirements placed on the data pipeline generally.
</blockquote></details>

Done.

**Review by stephen-soltesz — COMMENTED** [review]
You did the right thing with the NameValue struct. We don't need to depend on a third party repo for that.

A few more small comments. Are there more changes expected?

> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/2#-:-NOBocEd25UlleTDveiS:b-v8fcty)* status: 0 of 1 approvals obtained (waiting on @robertodauria)

___
*[`pkg/ndt8/model/measurement.go` line 8 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBpjio1WpkhgiTYiLe:-NOBpjio1WpkhgiTYiLf:b-upt912) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/model/measurement.go#L8)):*
> ```Go
> )
> 
> // WireMeasurement is a wrapper for Measurement structs that contains
> ```

s/contains/contain/
___
*[`pkg/ndt8/model/measurement.go` line 21 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBp_Qm3cS32Zd9pEeu:-NOBp_Qm3cS32Zd9pEev:b-540xti) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/model/measurement.go#L21)):*
> ```Go
> 	Server string `json:",omitempty"`
> 	// Measurement is the Measurement struct wrapped by this WireMeasurement.
> 	Measurement Measurement
> ```

If you place this as an embedded struct, I think the JSON serialization places all the fields inline rather than nested.
___
*[`pkg/ndt8/model/measurement.go` line 26 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBqvyq7opmheFMl3Mz:-NOBqvyq7opmheFMl3N-:bf2nrsj) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/model/measurement.go#L26)):*
> ```Go
> // The Measurement struct contains measurement results. This structure is
> // meant to be serialised as JSON as sent as a textual message. This
> // structure is specified in the ndt7 specification.
> ```

I don't understand the reference to "ndt7 specification." This `Measurement` structure is very different than ndt7's, no?
___
*[`pkg/ndt8/model/result.go` line 8 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBrEtcAIEMeMOKGHn9:-NOBrEtcAIEMeMOKGHnA:buniot) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/model/result.go#L8)):*
> ```Go
> 
> // NDT8Result is the struct that is serialized as JSON to disk as the archival
> // record of an ndt-m test.
> ```

Are we still using "ndtm"? If not, s/ndt-m/ndt8/
___
*[`pkg/ndt8/spec/spec.go` line 2 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBt5PV4N0CM3w_wabU:-NOBt5PV4N0CM3w_wabV:b-2l6j5z) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/spec/spec.go#L2)):*
> ```Go
> // Package spec contains constants for the ndt-m protocol. More information can
> // be found in the ndt7 protocol spec, of which ndt-m is an extension.
> ```

I recommend not referring to ndt7; this is a separate protocol spec.

And, I have the same question about ndt-m vs ndt8 throughout.

**Review by robertodauria — COMMENTED** [review]
I've addressed your comments and added `BytesSent` to both the design document and this PR. I don't expect to make any more changes.

> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/2#-:-NOF8xBt35QEqXq31lQn:b-ynlavk)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`pkg/ndt8/model/measurement.go` line 8 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBpjio1WpkhgiTYiLe:-NOF6Gvp3aEdcpxjSNAN:b4lik2h) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/model/measurement.go#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/contains/contain/
</blockquote></details>

This refers to "a wrapper", not "structs" (the wrapper contains information that doesn't need to be sent every time, not the Measurement struct). Why plural?
___
*[`pkg/ndt8/model/measurement.go` line 21 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBp_Qm3cS32Zd9pEeu:-NOF5HVO2fOwNXPNtvWF:be3wo1a) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/model/measurement.go#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If you place this as an embedded struct, I think the JSON serialization places all the fields inline rather than nested.
</blockquote></details>

Done (and verified that it works as advertised). Cool!
___
*[`pkg/ndt8/model/measurement.go` line 26 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBqvyq7opmheFMl3Mz:-NOF6mTIBWtkN2hbM6vk:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/model/measurement.go#L26)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I don't understand the reference to "ndt7 specification." This `Measurement` structure is very different than ndt7's, no?
</blockquote></details>

Done.
___
*[`pkg/ndt8/model/result.go` line 8 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBrEtcAIEMeMOKGHn9:-NOF6nOMA9RZjemvtVqZ:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/model/result.go#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are we still using "ndtm"? If not, s/ndt-m/ndt8/
</blockquote></details>

Done.
___
*[`pkg/ndt8/spec/spec.go` line 2 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBt5PV4N0CM3w_wabU:-NOF6oYBABcsvaobu0yK:b-896fix) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/spec/spec.go#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend not referring to ndt7; this is a separate protocol spec.

And, I have the same question about ndt-m vs ndt8 throughout.
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3, 1 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/msak/2#-:-NOFSZ-f4Mdvwo7btVGK:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`pkg/ndt8/model/measurement.go` line 8 at r4](https://reviewable.io/reviews/m-lab/msak/2#-NOBpjio1WpkhgiTYiLe:-NOFS1ttD4V7tZASU3JQ:b-a3alrg) ([raw file](https://github.com/m-lab/msak/blob/b976c473024222f5cd6442eaa72effaedf3b837b/pkg/ndt8/model/measurement.go#L8)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

This refers to "a wrapper", not "structs" (the wrapper contains information that doesn't need to be sent every time, not the Measurement struct). Why plural?
</blockquote></details>

Oh I see.

**Pull request merged**
